version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    target-branch: "dev"
    open-pull-requests-limit: 25
    labels:
      - "pip dependencies"
