name: Setup SSH, Python and Poetry
description: A simple action to setup everything, including dependencies.

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  ssh-key:
    description: The ssh-key
    required: true

runs:
  using: composite
  steps:
    - name: Setup access to private repo(s)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ inputs.ssh-key }}
    - name: Install poetry
      shell: bash
      run: pipx install poetry==1.8.5
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        cache: "poetry"
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: poetry install
