name: Setup SSH, UV and Python
description: A simple action to setup everything, including dependencies.

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  ssh-key:
    description: The ssh-key
    required: true

runs:
  using: composite
  steps:
    - name: Setup access to private repo(s)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ inputs.ssh-key }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: UV_GIT_LFS=1 uv sync --all-extras --dev
