repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.1
  hooks:
    - id: ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.1
  hooks:
    - id: ruff-format
      args: [--check]
- repo: https://github.com/lsst-ts/pre-commit-xmllint
  rev: v1.0.0
  hooks:
    - id: format-xmllint
