repos:
- repo: local
  hooks:
    - id: ruff-check
      name: Run ruff check before commit
      entry: uv run ruff check
      args: [--fix]
      language: system
      pass_filenames: false
    - id: ruff-format
      name: Run ruff format before commit
      entry: uv run ruff format
      language: system
      pass_filenames: false
    - id: xml-main-format
      name: Run ssrq fmt on main files before commit
      entry: uv run ssrq fmt "src/schema/*.xml" --option schema
      language: system
      pass_filenames: false
    - id: xml-common-format
      name: Run ssrq fmt on common files before commit
      entry: uv run ssrq fmt "src/schema/commons/*.xml" --option schema
      language: system
      pass_filenames: false
    - id: xml-element-format
      name: Run ssrq fmt on element files before commit
      entry: uv run ssrq fmt "src/schema/elements/*.xml" --option schema
      language: system
      pass_filenames: false
    - id: xml-example-format
      name: Run ssrq fmt on example files before commit
      entry: uv run ssrq fmt "src/schema/examples/*.xml"
      language: system
      pass_filenames: false
    - id: mypy
      name: Run mypy before commit
      entry: uv run mypy
      language: system
      types: [ python ]
      pass_filenames: false
    - id: mkdocs
      name: Run mkdocs before commit
      entry: uv run mkdocs build
      language: system
      pass_filenames: false
