copyright: Copyright &copy; 2023 SSRQ-SDS-FDS
docs_dir: src/docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SSRQ-SDS-FDS/ssrq-schema
      name: Schema of the SSRQ on GitHub
    - icon: fontawesome/solid/computer
      link: https://editio.ssrq-online.ch
      name: editio / digital scholarly edition
    - icon: material/information
      link: https://www.ssrq-sds-fds.ch/en/service-menu/contact/
      name: contact / imprint
  version:
    provider: mike
extra_css:
  - assets/css/extra.css
# This hook creates the odd and generates a markdown-file per element (de, fr)
hooks:
  - ./utils/docs/doc_hooks.py
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Base:
    - Transcription:
      - base/transcription/index.md
      - Print: base/transcription/print.md
      - Hand: base/transcription/hand.md
    - base/date.md
  #- Elements:
plugins:
  - search
  - i18n:
      default_language: de
      docs_structure: suffix
      languages:
        default:
          build: true
          name: Default (de)
          site_name: SSRQ Dokumentation
        fr:
          build: true
          name: Français
          site_name: SDS Documentation
      nav_translations:
        de:
          Base: Philologische Grundlagen
          Elements: Tag-Bibliothek
          Hand: B Handschriftliche Texte
          Home: Startseite
          Print: A Gedruckte Texte
          Transcription: Transkriptionsrichtlinien
        fr:
          Base: Bases philologiques
          Elements: Bibliothèque de tags
          Hand: B Textes manuscrits
          Home: Page d'accueil
          Print: A Textes imprimés
          Transcription: Principes de transcription
site_dir: build/site
site_name: !ENV [SITE_NAME, 'SSRQ Docs']
site_url: !ENV DOCS_URL
theme:
  favicon: assets/images/favicon-ssrq-32.png
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.top
  name: material
watch:
  - "src/docs/assets"
  - "src/docs/base"
  - "src/docs/translations"
  - "src/schema"
  - "utils"
