[project]
name = "ssrq-schema"
version = "0.1.0"
description = "TEI-ODD schema for the Swiss Law Sources with Python based tooling."
authors = [
    { name = "Bastian Politycki", email = "bastian.politycki@unisg.ch" },
    { name = "Christian Sonder", email = "christian.sonder@unisg.ch" },
    { name = "Pascale Sutter", email = "pascale.sutter@unisg.ch" },
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "lxml>=6.0.1",
    "mike>=2.1.3",
    "mkdocs-material>=9.6.18",
    "mkdocs-static-i18n>=1.3.0",
    "pydantic>=2.11.7",
    "pyschval",
    "pyuca>=1.2",
    "requests>=2.32.5",
    "rich>=14.1.0",
    "ruff>=0.12.11",
    "saxonche>=12.8.0",
    "semver>=3.0.4",
    "snakemd>=2.3.0",
    "ssrq-cli",
]

[dependency-groups]
dev = [
    "lxml-stubs>=0.5.1",
    "mypy>=1.17.1",
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-xdist>=3.8.0",
    "saxonche-stubs>=0.7.2",
    "types-requests>=2.32.4.20250809",
]

[build-system]
build-backend = 'hatchling.build'
requires = ['hatchling']

[tool.hatch.build.targets.wheel]
include = ["utils"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
files = ["utils"]
ignore_missing_imports = true

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
ignore = ["E501"]
select = ["C90", "E", "F", "I001", "RET", "UP"]

[tool.uv.sources]
ssrq-cli = { git = "ssh://git@github.com/SSRQ-SDS-FDS/ssrq-cli", branch = "main" }
pyschval = { git = "https://github.com/SSRQ-SDS-FDS/py-schematron-validator" }
