[ssrq.schema.meta]
authors = ["Bastian Politycki <bastian.politycki@unisg.ch>", "Pascale Sutter <pascale.sutter@unisg.ch>"]
schemas = [{title="SSRQ Editionsrichtlinien", description = "The main schema used by the Swiss Law Sources to validate TEI XML transcriptions", entry = "main.odd.xml", name="TEI_Schema", version="1.0.0-alpha.1", tei_version="4.5.0"}]

[tool.poetry]
name = "ssrq-schema"
packages = [
    { include = "utils/*.py" },
]
version = "0.1.0"
description = "TEI-ODD schema for the Swiss Law Sources with Python based tooling."
authors = ["Bpolitycki <bastian.politycki@unisg.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
saxonche = "^12.0.0"
pydantic = "^1.10.5"
semver = "^3.0.1"
saxonche-stubs = "^0.4.0"
requests = "^2.30.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.2.1"
ruff = "^0.0.261"
pyschval = {git = "https://github.com/SSRQ-SDS-FDS/py-schematron-validator.git", rev = "main"}
ssrq-cli = {git = "ssh://git@github.com/SSRQ-SDS-FDS/ssrq-cli.git", rev = "main"}
pytest-xdist = "^3.2.0"
mypy = "^1.3.0"
types-requests = "^2.31.0.1"
pre-commit = "^3.3.3"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.1.15"
mkdocs-static-i18n = "^0.56"
snakemd = "^2.1.0"
mike = "^1.1.2"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[tool.mypy]
files = ["utils/*.py"]

[tool.ruff]
select = ["E", "F", "I001"]
ignore = ["E501"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
