#!/bin/bash

src='.'

function cmd {
  # Run any command you want
  poetry run "${@}"
}

function fmt {
  cmd black . "${@}"
  cmd ruff --fix . "${@}"
}

function fmt-check {
    echo "Checking the format with black..."
    cmd black --check ${src}
}

function lint-only {
    echo "Linting using ruff..."
    cmd ruff ${src}
}

function lint {
    fmt-check
    lint-only
}

function test {
    lint

    output=$(validate 2>&1) # Execute the command and capture the output – stderr will go to stdout.

    if echo "$output" | grep -q "Some files are not"; then
        echo "$output"
        exit 1
    fi

    echo "Running tests using pytest..."
    cmd pytest -n 4 "${@}"
}

function test-only {
    cmd pytest -n 4 "${@}"
}

function compile {
    validate
    cmd python utils/main.py
}

function validate {
    echo "Checking the xml sources..."
    cmd python utils/validate.py
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
