#!/bin/bash

src='.'

function cmd {
  # Run any command you want
  uv run "${@}"
}


function check {
  cmd ruff format . "${@}"
  cmd ruff check --fix . "${@}"
  cmd mypy
}

function install {
    echo "Installing dependencies..."
    UV_GIT_LFS=1 uv sync
    echo "Installing pre-commit hooks..."
    cmd pre-commit install
}

function test {
    cmd pytest -n auto "${@}"
}

function compile {
    validate
    cmd python utils/schema/compile.py
}

function build-docs {
    cmd mkdocs build
}

function serve-docs {
    cmd mkdocs serve
}

function validate {
    echo "Checking the xml sources..."
    cmd python utils/schema/validate.py
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
