name: Deploy using mike
description: A action which deploys an mkdocs site using mike.

inputs:
  version-name:
    description: The name of the version as well as the name of the target folder
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git user
      shell: bash
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
    - name: Deploy dev
      if: ${{ inputs.version-name == 'dev' }}
      run: |
        if poetry run mike list | grep -q "dev"; then
          dev_exists=true
        else
          dev_exists=false
        fi

        if $dev_exists; then
          poetry run mike delete dev --push
        fi

        poetry run mike deploy dev --push

        if poetry run mike list | grep -q "latest"; then
          latest_exists=true
        else
          latest_exists=false
        fi

        if ! $latest_exists; then
          poetry run mike set-default dev --push
        fi

      shell: bash
    - name: Deploy concrete docs version
      if: ${{ inputs.version-name == 'main' }}
      run: |
        VERSION_NUMBER=$(grep -oE '"SLS TEI-Schema".*\sversion\s?=\s?"([0-9a-zA-Z.-]+)"' pyproject.toml | sed -n 's/.*version = "\(.*\)".*/\1/p')
        poetry run mike deploy ${VERSION_NUMBER} latest --update-aliases --no-redirect --push
        poetry run mike set-default latest --push
      shell: base
