name: test_and_publish_dev

on:
  pull_request:
    branches: ['dev']
  push:
    branches: ['dev']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          persist-credentials: false
          token: ${{ secrets.TEI_VOLUMES_PAT }}
      - name: Setup SSH and Python with Poetry
        uses: ./.github/actions/setup
        with:
          ssh-key: ${{ secrets.CLI_SECRET_KEY }}
      - name: Setup xmllint
        uses: Bpolitycki/setup-xmllint-action@1.0.1
      - name: Check the formatting of .py-files
        run: ./Taskfile fmt-check
      - name: Check the formatting of .xml-files
        run: ./Taskfile fmt-xml
      - name: Lint all .py-files
        run: ./Taskfile lint-only
      - name: Validate all schema source files
        run: ./Taskfile validate
      - name: Run all tests using pytest
        run: poetry run pytest -n auto
      - name: Build docs
        run: ./Taskfile build-docs
      - name: Check links in docs
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: src/docs/**/*.md --exclude '^file:' --timeout 60
          fail: true

  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: test
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PRE_COMMIT_ALLOW_NO_CONFIG: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.TEI_VOLUMES_PAT }}
      - name: Setup SSH and Python with Poetry
        uses: ./.github/actions/setup
        with:
          ssh-key: ${{ secrets.CLI_SECRET_KEY }}
      - name: Set docs-url
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo "DOCS_URL=${url}" >> "$GITHUB_ENV"
      - name: Setup GitHub Token for Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Build and publish
        uses: ./.github/actions/mike
        with:
          version-name: 'dev'
